language: ruby
cache: bundler

rvm:
  - 2.6
  - 3.0

env:
  - DB=pg
  - DB=mysql2
  - DB=sqlite3

gemfile:
  - gemfiles/gemfile_60.gemfile
  - gemfiles/gemfile_61.gemfile

# rails 5.2
jobs:
  include:
    - env: DB=pg
      rvm: 2.6
      gemfile: gemfiles/gemfile_52.gemfile
    - env: DB=mysql2
      rvm: 2.6
      gemfile: gemfiles/gemfile_52.gemfile
    - env: DB=sqlite3
      rvm: 2.6
      gemfile: gemfiles/gemfile_52.gemfile

services:
  - mysql
  - postgresql

before_script:
  - mysql -e 'create database ancestry_test;' || true
  - psql -c 'create database ancestry_test;' -U postgres || true
