sudo: false

rvm:
  - 2.2.7
  - 2.3.4
  - 2.4.1

gemfile:
  - gemfiles/mysql_ar_42.gemfile
  - gemfiles/mysql2_ar_50.gemfile
  - gemfiles/mysql2_ar_51.gemfile
  - gemfiles/pg_ar_42.gemfile
  - gemfiles/pg_ar_50.gemfile
  - gemfiles/pg_ar_51.gemfile
  - gemfiles/sqlite3_ar_42.gemfile
  - gemfiles/sqlite3_ar_50.gemfile
  - gemfiles/sqlite3_ar_51.gemfile

matrix:
  include:
    - rvm: 1.9.3
      gemfile: gemfiles/mysql_ar_32.gemfile
    - rvm: 1.9.3
      gemfile: gemfiles/pg_ar_32.gemfile
    - rvm: 1.9.3
      gemfile: gemfiles/sqlite3_ar_32.gemfile
  exclude:
    - rvm: 2.4.1
      gemfile: gemfiles/mysql_ar_42.gemfile

services:
  - mysql
  - postgresql

before_script:
  - mysql -e 'create database ancestry_test;' || true
  - psql -c 'create database ancestry_test;' -U postgres || true
